apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1-hadoop
  labels:
    app: p1-hadoop
spec:
  selector:
     matchLabels:
       app: p1-hadoop
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: p1-hadoop
    spec:
      containers:
        # - image: sequenceiq/hadoop-docker:latest
        - image: ibmcom/iop-hadoop:latest
          imagePullPolicy: Always
          name: p1-hadoop
          ports:
            - containerPort: 50070