apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1-sonarqube
  labels:
    app: p1-sonarqube
spec:
  selector:
     matchLabels:
       app: p1-sonarqube
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: p1-sonarqube
    spec:
      containers:
        # - image: sonarqube:latest
        - image: sonarqube:community
          imagePullPolicy: Always
          name: p1-sonarqube
          ports:
            - containerPort: 9000